### ISSUE TITLE
Add a picture of the coated temperature sensor

### ISSUE THREAD

**Issue by charlesfleche** [zanhecht/SousVide#1]
Would it be possible to add a picture of the sensor after the aquarium sealant and heat shrinking process ? It'd be great to have an idea on how it's supposed to look like for the less handy of us...

Great project, thanks for sharing !

**Comment by zanhecht** [comment]
I added a picture of the sensor to http://zansstuff.com/sous-vide

**Comment by charlesfleche** [comment]
Thanks !
